INFO:    Converting SIF file to temporary sandbox...
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
You are using fMRIPrep-20.2.0, and a newer version of fMRIPrep is available: 20.2.4.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
WARNING: Version 20.2.0 of fMRIPrep (current) has been FLAGGED
(reason: Functional outputs in standard space can be wrong depending on the original data's orientation headers - see https://github.com/nipreps/fmriprep/issues/2307).
That means some severe flaw was found in it and we strongly
discourage its usage.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 321, in init_single_subject_wf
    ('outputnode.fsnative2t1w_xfm', 'inputnode.fsnative2t1w_xfm')]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 158, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 766, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "func_preproc_ses_1_task_rest_run_1_wf" found.
INFO:    Cleaning up image...
FATAL:   could not open image /data/aglinska/fmriprep.simg: failed to retrieve path for /data/aglinska/fmriprep.simg: lstat /mmfs1/data/aglinska/fmriprep.simg: no such file or directory
/cm/local/apps/slurm/var/spool/job270572/slurm_script: line 47: /data/aglinska/data/ABIDE2/Derivatives/test/sub-28893: No such file or directory
/cm/local/apps/slurm/var/spool/job270572/slurm_script: line 48: /data/aglinska/data/ABIDE2/Derivatives/test/sub-28893.html: No such file or directory
INFO:    Converting SIF file to temporary sandbox...
WARNING: skipping mount of /data/aglinska/scratch: stat /data/aglinska/scratch: no such file or directory
INFO:    Cleaning up image...
FATAL:   container creation failed: mount /data/aglinska/scratch->/scratch error: while mounting /data/aglinska/scratch: mount source /data/aglinska/scratch doesn't exist
